services:
  store_api:
    image: node:22.11.0
    container_name: store_api
    volumes:
      - ~/proyectos/backend_nestjs_platzi:/usr/src/app
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=dev
    command: npm run start:dev
    ports:
      - "3000:3000"
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=store
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - postgres
